site_name: Plataforma UNOData
locale: es
nav:
  - 'Guía de usuario':
    - 'Acceso': 'access/access.md'
    - 'Gestión':
      - "Perfil":
        - 'Gestión de Mi Perfil': 'management/profile/profile.md'
        - 'Idioma': 'management/profile/language.md'
      - "Organización":
        - 'Gestión de Mi Organización': 'management/organization/organization.md'
        - 'Usuarios': 'management/organization/users.md'
      - "Entidades":
        - "Servicio web": "management/entities/service.md"
        - "Capa": "management/entities/layer.md"
        - "Mapa": "management/entities/map.md"
        - "Aplicación": "management/entities/application.md"
    - "Aplicaciones":
      - "UNOVida": "app/unovida.md"
      - "UNOLocaliza": "app/unolocaliza.md"
      - "UNOAfecta": "app/unoafecta.md"
  - Sobre:
    - 'Licencia': 'about/license.md'
    - 'Versión': 'about/release-notes.md'

theme: 
  name: 'material'
  language: 'es'
  palette:
      primary: 'indigo'
      accent: 'indigo'
  font:
      text: 'Montserrat Light'
      code: 'Roboto Mono'
  favicon: img/cropped-UNO-32x32.png
  logo: img/cropped-UNO-32x32.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
# extra_css:
#   - stylesheets/unodata.css

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
  generator: false

copyright: Copyright 2024 [Urban Node Observatory](https://unodata.es/)